- hosts: localhost
  tasks:
   - name: "test_nginx_pv"
     shell: ansible-playbook test-nginx-pvs.yml 
     args:
       chdir: "{{ playbook_dir }}/tests/"
     ignore_errors: true

   - name: "test_init_containers"
     shell: ansible-playbook test-init-containers.yml
     args:
       chdir: "{{ playbook_dir }}/tests/"
     ignore_errors: true
